-- تحديث جدول المستخدمين (Users)
ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS "fullName" TEXT,
ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'active',
ADD COLUMN IF NOT EXISTS "allowedDevice" TEXT DEFAULT 'all',
ADD COLUMN IF NOT EXISTS "lastActive" BIGINT,
ADD COLUMN IF NOT EXISTS "currentPage" TEXT,
ADD COLUMN IF NOT EXISTS "isOnline" BOOLEAN DEFAULT false;

-- تحديث جدول الأقسام
ALTER TABLE public.categories 
ADD COLUMN IF NOT EXISTS "order" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "parentId" UUID,
ADD COLUMN IF NOT EXISTS "isHidden" BOOLEAN DEFAULT false;

-- تحديث جدول المنتجات
ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS "price" NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS "dozenPriceUsd" NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS "piecePriceUsd" NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS "piecePriceIqd" NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS "packaging" TEXT,
ADD COLUMN IF NOT EXISTS "piecesCount" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "modelNumber" TEXT,
ADD COLUMN IF NOT EXISTS "productCode" TEXT,
ADD COLUMN IF NOT EXISTS "barcode" TEXT,
ADD COLUMN IF NOT EXISTS "categoryId" UUID,
ADD COLUMN IF NOT EXISTS "subcategoryId" UUID,
ADD COLUMN IF NOT EXISTS "finalImageUrl" TEXT,
ADD COLUMN IF NOT EXISTS "views" INTEGER DEFAULT 0;

-- Refresh Supabase Schema Cache
NOTIFY pgrst, 'reload schema';
